// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddActivityWithDB(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddActivityWithDB'](arg1, arg2, arg3, arg4, arg5);
}

export function LoadCategories() {
  return window['go']['main']['App']['LoadCategories']();
}

export function SaveCategory(arg1) {
  return window['go']['main']['App']['SaveCategory'](arg1);
}
