// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PrintHelloWorld(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['PrintHelloWorld'](arg1, arg2, arg3, arg4, arg5);
}
