// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddActivityWithDB(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function AddColumn(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddEmptyRow(arg1:string):Promise<void>;

export function AddTestData(arg1:string,arg2:string,arg3:any):Promise<void>;

export function ColumnExists(arg1:string,arg2:string):Promise<boolean>;

export function DeleteColumn(arg1:string,arg2:string):Promise<void>;

export function DeleteRow(arg1:number):Promise<void>;

export function GetButtonNames():Promise<Array<string>>;

export function GetColumnNames(arg1:string):Promise<Record<string, string>>;

export function GetTableData(arg1:string):Promise<Array<Record<string, any>>>;

export function GetTestData():Promise<Array<Record<string, any>>>;

export function GetWindowSize():Promise<number|number>;

export function LoadCategories():Promise<Array<string>>;

export function ResizeWindow(arg1:number,arg2:number):Promise<void>;

export function SaveCategory(arg1:string):Promise<void>;

export function SetSettings(arg1:string,arg2:number):Promise<void>;

export function UpdateCellValue(arg1:number,arg2:string,arg3:any):Promise<void>;

export function UpdateColumnName(arg1:string,arg2:string):Promise<void>;
