// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddActivityWithDB(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function AddTestData(arg1:string,arg2:string,arg3:number):Promise<void>;

export function GetTestData():Promise<Array<Record<string, any>>>;

export function GetWindowSize():Promise<number|number>;

export function LoadCategories():Promise<Array<string>>;

export function ResizeWindow(arg1:number,arg2:number):Promise<void>;

export function SaveCategory(arg1:string):Promise<void>;

export function SetSettings(arg1:string,arg2:number):Promise<void>;

export function UpdateCellValue(arg1:number,arg2:string,arg3:string):Promise<void>;
